"""add tag

Revision ID: 70a9b88915db
Revises: e0f6ee5fe722
Create Date: 2026-08-27 01:08:21.008036

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a9b88915db'
down_revision: Union[str, Sequence[str], None] = 'e0f6ee5fe722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    # ### end Alembic commands ###

    ### Add tag entries in the database
    op.execute("""
        INSERT INTO tag (id, name, instruction) VALUES
        ('00000000-0000-0000-0000-000000000001', 'EXPRESS', 'Prioritize this shipment for the fastest available delivery.'),
        ('00000000-0000-0000-0000-000000000002', 'STANDARD', 'Handle and deliver this shipment using standard service.'),
        ('00000000-0000-0000-0000-000000000003', 'FRAGILE', 'Handle this shipment carefully to prevent damage to delicate contents.'),
        ('00000000-0000-0000-0000-000000000004', 'HEAVY', 'Use equipment and handling procedures suitable for a heavy shipment.'),
        ('00000000-0000-0000-0000-000000000005', 'INTERNATIONAL', 'Complete the required international customs and shipping procedures.'),
        ('00000000-0000-0000-0000-000000000006', 'DOMESTIC', 'Process this shipment for delivery within the domestic network.'),
        ('00000000-0000-0000-0000-000000000007', 'TEMPERATURE_CONTROLLED', 'Keep this shipment within its required temperature range during transit.'),
        ('00000000-0000-0000-0000-000000000008', 'GIFT', 'Preserve the gift presentation and do not include pricing information.'),
        ('00000000-0000-0000-0000-000000000009', 'RETURN', 'Route this shipment through the return handling process.'),
        ('00000000-0000-0000-0000-000000000010', 'DOCUMENTS', 'Protect and deliver the documents without folding or damaging them.')
    """)
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
