"""adding the shipment event

Revision ID: 960a21f78163
Revises: 2d12d86a88cd
Create Date: 2026-08-15 10:20:14.096262

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '960a21f78163'
down_revision: Union[str, Sequence[str], None] = '2d12d86a88cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM(name="shipmentstatus", create_type=False), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('seller', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('seller', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.drop_column('shipment', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'), autoincrement=False, nullable=False))
    op.drop_column('seller', 'zip_code')
    op.drop_column('seller', 'address')
    op.drop_table('shipment_event')
    # ### end Alembic commands ###
