"""add unique constraint to seller email

Revision ID: e3368b1ff87d
Revises: 960a21f78163
Create Date: 2026-08-16 14:20:53.910343

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3368b1ff87d'
down_revision: Union[str, Sequence[str], None] = '960a21f78163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_delivery_partner_email'), 'delivery_partner', ['email'], unique=True)
    op.create_index(op.f('ix_seller_email'), 'seller', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_email'), table_name='seller')
    op.drop_index(op.f('ix_delivery_partner_email'), table_name='delivery_partner')
    # ### end Alembic commands ###
