"""add client contact

Revision ID: ed72a020013e
Revises: e26d8213e465
Create Date: 2026-08-17 08:50:21.137418

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed72a020013e'
down_revision: Union[str, Sequence[str], None] = 'e26d8213e465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('client_contact_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contact_phone')
    op.drop_column('shipment', 'client_contact_email')
    # ### end Alembic commands ###
